namespace AtelierTomato.Markov.Bot.Discord.Core
{
	public enum HelpSubject
	{
		Unknown,
		General,
		Scope,
		Location,
		OptIn,
		OptOut,
		DeletePermission,
		PermissionsUser,
		PermissionsServer,
		PermissionsAll,
		Speak,
		Mimic,
		SpeakStartsWith,
		SpeakKeyword,
		Global,
		SetLocationGroup,
		LocationGroup,
		CreateLocationGroup,
		RenameLocationGroup,
		DeleteLocationGroup,
		InviteLocation,
		AcceptLocationGroupInvite,
		DenyLocationGroupInvite,
		UpdateLocation,
		RemoveLocation,
		LocationGroupRequestList,
		LocationGroupList,
		LocationGroupInfo,
	}
}
