<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>903a6383-3b11-4072-94cf-040d6de3e39b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net.WebSocket" Version="3.17.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.0" />
    <PackageReference Include="Tmds.Systemd.Logging" Version="0.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtelierTomato.Markov.Bot.Discord.Core\AtelierTomato.Markov.Bot.Discord.Core.csproj" />
  </ItemGroup>
</Project>
